FROM bref/php-82:2

# Install aws-lambda-rie to allow local testing
# This is the x86_64 version even though the URL doesn't specify architecture
RUN curl -Lo /usr/local/bin/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod +x /usr/local/bin/aws-lambda-rie

WORKDIR /var/task

# Copy x86_64-specific PHP configuration
COPY php/conf.d/php.ini.x86_64 /var/task/php/conf.d/php.ini

ENTRYPOINT ["/var/task/entrypoint.sh"]