FROM bref/php-82-fpm-dev:2

WORKDIR /var/task

# x86_64 needs PDO PostgreSQL to be explicitly loaded
# Create the symlink in the Dockerfile to make it explicit
COPY php/conf.d/pdo_extension.ini.sample /opt/bref/etc/php/conf.d/99-pdo_pgsql.ini

ENTRYPOINT ["/var/task/api-entrypoint.sh"]